# fly.toml app configuration file generated for bbs-lingering-paper-8912 on 2024-02-22T15:40:32-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bbs-lingering-paper-8912'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
