name: Go
on:
    pull_request:
    push:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
                  run_install: true
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.21.x"
            - name: Install dependencies
              run: |
                  go mod download
                  go mod verify
                  go install github.com/a-h/templ/cmd/templ@latest
                  templ generate
                  pnpm run build
            - name: Build
              run: go build -v ./...
            - name: Test with the Go CLI
              run: go test ./...
